# -*- coding: utf-8 -*-
"""Web_Scraping_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175-pBgTJtu_lYn0lKTqu1s6j4cLfzzWD
"""

!pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "http://quotes.toscrape.com"
response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

quotes = soup.find_all("span", class_="text")
authors = soup.find_all("small", class_="author")

data = []

for q, a in zip(quotes, authors):
    data.append({
        "Quote": q.text,
        "Author": a.text
    })

df = pd.DataFrame(data)

df

df.to_csv("quotes.csv", index=False)

from google.colab import files
files.download("quotes.csv")

import matplotlib.pyplot as plt

df["Author"].value_counts().head(10).plot(kind="bar")
plt.title("Top Authors")
plt.show()

from google.colab import files
files.download('quotes.csv')

df